# Generated by Django 3.0.2 on 2020-03-18 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finch',
        ),
    ]
