# Generated by Django 3.0.2 on 2020-03-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200319_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='type',
            new_name='name',
        ),
    ]
